version: '3.8'

services:
  api: 
    build:
      dockerfile: api.Dockerfile
      context: .
    ports:
      - "3000:3000"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - api